import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dircryptex: directory of cryptocurrency exchanges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://www.coingecko.com/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Dircryptex</h2>
        <p className={styles.description}>
          Directory of cryptocurrency exchanges
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.coingecko.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              src="https://static.coingecko.com/s/coingecko-logo-8903d34ce19ca4be1c81f0db30e924154750d208683fad7ae6f2ce06c76d0a56.png"
              alt="Coingecko Logo"
              width={200}
              height={50}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
